version: '3.7'

services:
  ft_nike:      
    build:
      context: ./
      dockerfile: Dockerfile
    

    restart: always 

    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external: true

