version: '3.7'

x-compose-config:
  project_name: restaurant

services:
  frontend:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: ft_nike

      
    volumes:
      - ./:/app

    ports:
      - '4010:5173'

